---
title: "Untitled"
author: "Gabe Runte"
date: "2023-02-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("my_functions.R")
setup_libs()
```

## for() loops! 

The for() loop is a very useful and versatile tool in basic programming. They allow us to perform tasks over and over again without retyping or rerunning code! They are ubiquitous across languages (R, python, java, etc.) so making friends with the structure can pay even bigger dividends if you may have to perform tasks ourside of R as well. 


### Intro to loops
```{r}
x = seq(0, 100, by = 10) 
x
y = numeric() #empty vector for our for() loop to fill
y

# We'll start by writing a for() loop that iterates over the entirety of the vector we just created
for(i in 1:length(x)){
 y[i]= x[i] +5  # for each position (i) in the vector x, add 5 and save it to the corresponding position in vector y
}

y

# "But we could have just done that with vector math in R! Why do we need a for()loop for that?" You don't. But it's useful to get to know the structure first!  
x+5
```

```{r, message = F}
#let's try something a bit more practical


asv = read_data("asv_table.csv") %>% #woohoo! we get to use another one of our custom functions
  rename(seq = x1) 

asv_table = matrix(asv[,2:ncol(asv)], ncol = ncol(asv)-1, nrow = nrow(asv))

row.names(asv_table) = asv_table$seq

dim(asv_table)
head(asv_table)

asv_rra = matrix(nrow = nrow(asv_table), ncol = ncol(asv_table)) #setup empty matrix to hold our new data
asv_rra[,1] = asv_table[,1]

dim(asv_rra)
for(i in 2:ncol(asv_table)){
  sum = sum(asv_table[,i])
  
  asv_rra[,i] = asv_table[,i]/sum
  
}


```












```{r, message = F}
#let's try out another one of our functions!
asv = read_data("asv_table.csv") %>% 
  rename(seq = x1)
```

